version: '3'
services:
  jersey:
    build:
      context: .
      dockerfile: ./jersey/Dockerfile
    volumes:
      - ./jersey:/app/appsrc
      - ./jersey/tcell:/app/tcell
      - ~/.m2:/root/.m2
    ports:
      - 8080:8080


  struts2-exploit:
    build:
      context: .
      dockerfile: ./struts2-exploit/Dockerfile
    volumes:
      - ./struts2-exploit/tcell:/app/tcell
    ports:
      - 8081:8080

  jenkins-exploit:
    build:
      context: .
      dockerfile: ./jenkins-exploit/Dockerfile
    volumes:
      - ./jenkins-exploit/tcell:/app/tcell
    ports:
      - 8082:8080

  jenkins-exploit-exec:
    build:
      context: ./jenkins-exploit/
      dockerfile: exploit.Dockerfile
